import { LearningRoadmap } from '@/types/playlist';

export const CURATED_ROADMAPS: LearningRoadmap[] = [
  {
    id: 'roadmap-nextjs-fullstack',
    title: 'Full-Stack Next.js & Modern React',
    slug: 'nextjs-fullstack',
    tagline: 'Master modern web development from TypeScript foundations to high-scale production Next.js 15 apps.',
    description: 'A comprehensive, end-to-end curriculum for modern web engineering. Covers TypeScript, React 19 architecture, Next.js 15 App Router, Server Actions, Tailwind CSS, Prisma/Drizzle ORM, and cloud deployments.',
    category: 'Frontend',
    icon: 'Code2',
    level: 'Intermediate',
    estimatedWeeks: 8,
    color: '#6366f1',
    milestones: [
      {
        id: 'ms-next-1',
        title: 'Modern TypeScript & JavaScript Deep Dive',
        description: 'Generics, Utility Types, Async/Await patterns, Event Loop, closures, and ESNext features.',
        estimatedHours: 12,
        skills: ['TypeScript', 'Generics', 'Async/Await', 'ESNext'],
      },
      {
        id: 'ms-next-2',
        title: 'React 19 Architecture & State Management',
        description: 'Server Components vs Client Components, custom hooks, context, useOptimistic, and performance profiling.',
        estimatedHours: 18,
        skills: ['React 19', 'Hooks', 'Server Components', 'Suspense'],
      },
      {
        id: 'ms-next-3',
        title: 'Next.js 15 App Router & Server Actions',
        description: 'Nested layouts, dynamic routes, streaming, Server Actions, middleware, route handlers, and caching strategy.',
        estimatedHours: 24,
        skills: ['Next.js 15', 'App Router', 'Server Actions', 'Streaming'],
      },
      {
        id: 'ms-next-4',
        title: 'Database Architecture, Auth & Cloud Deployments',
        description: 'PostgreSQL, Drizzle/Prisma ORMs, OAuth/JWT Auth, edge middleware, and Cloud Run / Vercel deployments.',
        estimatedHours: 20,
        skills: ['PostgreSQL', 'Drizzle ORM', 'OAuth', 'Cloud Deployment'],
      },
    ],
  },
  {
    id: 'roadmap-dsa-algorithms',
    title: 'Data Structures & Algorithms (DSA)',
    slug: 'dsa-algorithms',
    tagline: 'Systematic mastery of coding patterns, algorithmic thinking, and technical interview problem-solving.',
    description: 'Designed for software engineers preparing for top-tier technical interviews and algorithmic mastery. Progresses from fundamental data structures to advanced graph theory and dynamic programming.',
    category: 'Algorithms',
    icon: 'Binary',
    level: 'All Levels',
    estimatedWeeks: 10,
    color: '#10b981',
    milestones: [
      {
        id: 'ms-dsa-1',
        title: 'Big-O Analysis, Arrays & Two-Pointer Patterns',
        description: 'Time & space complexity analysis, sliding window technique, prefix sums, and two-pointer intervals.',
        estimatedHours: 14,
        skills: ['Big-O', 'Sliding Window', 'Two Pointers', 'Prefix Sums'],
      },
      {
        id: 'ms-dsa-2',
        title: 'Linked Lists, Stacks, Queues & Hash Tables',
        description: 'Monotonic stacks, fast & slow pointers, hash collisions, LRU Cache implementation, and queue simulations.',
        estimatedHours: 16,
        skills: ['Linked Lists', 'Monotonic Stack', 'LRU Cache', 'Hashing'],
      },
      {
        id: 'ms-dsa-3',
        title: 'Trees, Binary Search Trees, Heaps & Graphs',
        description: 'Tree traversals, Trie, Priority Queues, DFS/BFS graph exploration, Dijkstra, and Topological Sort.',
        estimatedHours: 25,
        skills: ['Binary Trees', 'BST', 'Heaps', 'Graph BFS/DFS', 'Dijkstra'],
      },
      {
        id: 'ms-dsa-4',
        title: 'Dynamic Programming & Backtracking Patterns',
        description: '1D & 2D memoization, knapsack variations, subset generation, N-Queens backtracking, and state machines.',
        estimatedHours: 25,
        skills: ['1D/2D DP', 'Knapsack', 'Backtracking', 'State Transitions'],
      },
    ],
  },
  {
    id: 'roadmap-system-design',
    title: 'System Design & Distributed Backend',
    slug: 'system-design',
    tagline: 'Architect resilient, scalable, high-throughput microservices and distributed storage systems.',
    description: 'Master large-scale system architecture: load balancing, horizontal partitioning, distributed caching (Redis), event streaming (Kafka), consensus protocols, and rate limiters.',
    category: 'Backend & Systems',
    icon: 'Server',
    level: 'Advanced',
    estimatedWeeks: 8,
    color: '#f59e0b',
    milestones: [
      {
        id: 'ms-sys-1',
        title: 'Networking, Protocols & API Gateways',
        description: 'HTTP/2, HTTP/3, WebSockets, gRPC, reverse proxies (Nginx), and API Gateway rate-limiting.',
        estimatedHours: 15,
        skills: ['gRPC', 'WebSockets', 'Nginx', 'Rate Limiting'],
      },
      {
        id: 'ms-sys-2',
        title: 'Relational vs NoSQL, Sharding & Caching',
        description: 'ACID vs BASE, B-Trees vs LSM-Trees, Redis caching strategies (Cache-Aside, Write-Through), and consistent hashing.',
        estimatedHours: 20,
        skills: ['PostgreSQL', 'Redis', 'Consistent Hashing', 'Sharding'],
      },
      {
        id: 'ms-sys-3',
        title: 'Message Brokers & Event-Driven Architecture',
        description: 'Apache Kafka vs RabbitMQ, event sourcing, idempotent consumers, and saga pattern for distributed transactions.',
        estimatedHours: 22,
        skills: ['Kafka', 'Event Streaming', 'Saga Pattern', 'Idempotency'],
      },
      {
        id: 'ms-sys-4',
        title: 'High Availability, Consensus & Case Studies',
        description: 'CAP Theorem, Raft/Paxos consensus, Designing YouTube/Netflix video ingestion, and real-time chat architecture.',
        estimatedHours: 25,
        skills: ['CAP Theorem', 'Distributed Consensus', 'Video Streaming Arch', 'Real-time Chat'],
      },
    ],
  },
  {
    id: 'roadmap-ai-engineering',
    title: 'AI & Gemini Agentic Engineering',
    slug: 'ai-engineering',
    tagline: 'Build next-generation generative AI applications, multimodal pipelines, and autonomous agent loops.',
    description: 'Learn how to build production-grade AI applications using Google Gemini API, structured outputs, function calling, multimodal inputs, Vector DBs (Chroma/Pinecone), RAG, and agentic workflows.',
    category: 'AI & Machine Learning',
    icon: 'Sparkles',
    level: 'Intermediate',
    estimatedWeeks: 6,
    color: '#ec4899',
    milestones: [
      {
        id: 'ms-ai-1',
        title: 'LLM Foundations & Prompt Engineering',
        description: 'Tokenization, temperature/top-k sampling, few-shot prompting, and schema-constrained JSON outputs.',
        estimatedHours: 10,
        skills: ['Prompt Engineering', 'Structured JSON', 'Sampling Parameters'],
      },
      {
        id: 'ms-ai-2',
        title: 'Gemini 2.5/3.5 SDK & Function Calling',
        description: 'Google GenAI SDK, Tool use / Function calling, Tool declarations, and server-side proxy security.',
        estimatedHours: 16,
        skills: ['Gemini API', '@google/genai', 'Function Calling', 'Tool Use'],
      },
      {
        id: 'ms-ai-3',
        title: 'Retrieval-Augmented Generation (RAG) & Vector Search',
        description: 'Text embeddings, chunking strategies, Vector Databases, hybrid search, and semantic document Q&A.',
        estimatedHours: 20,
        skills: ['Embeddings', 'Vector Search', 'RAG Pipeline', 'Semantic Retrieval'],
      },
      {
        id: 'ms-ai-4',
        title: 'Autonomous Agents, Memory & Multi-Step Reasoning',
        description: 'ReAct loops, human-in-the-loop validation, conversational memory stores, and self-correcting agent chains.',
        estimatedHours: 22,
        skills: ['ReAct Agents', 'Multi-agent Systems', 'Conversational Memory', 'Self-Reflection'],
      },
    ],
  },
  {
    id: 'roadmap-devops-cloud',
    title: 'DevOps, Containers & Cloud Infrastructure',
    slug: 'devops-cloud',
    tagline: 'Containerize, orchestrate, and automate CI/CD pipelines on Google Cloud and AWS.',
    description: 'Master modern DevOps engineering: Docker containerization, Kubernetes cluster orchestration, GitHub Actions CI/CD automation, Terraform Infrastructure as Code (IaC), and observability.',
    category: 'DevOps & Cloud',
    icon: 'Cloud',
    level: 'Intermediate',
    estimatedWeeks: 8,
    color: '#06b6d4',
    milestones: [
      {
        id: 'ms-devops-1',
        title: 'Linux Internals, Shell Scripting & Git Ops',
        description: 'Systemd, networking tools (curl, netstat), bash automation, SSH keys, and advanced Git branch workflows.',
        estimatedHours: 12,
        skills: ['Linux CLI', 'Bash Scripting', 'Git Hooks', 'Networking'],
      },
      {
        id: 'ms-devops-2',
        title: 'Docker Containerization & Multi-Stage Builds',
        description: 'Dockerfile optimization, layers caching, volumes, networks, compose orchestration, and security scanning.',
        estimatedHours: 16,
        skills: ['Docker', 'Multi-stage Builds', 'Docker Compose', 'Container Security'],
      },
      {
        id: 'ms-devops-3',
        title: 'Kubernetes (K8s) Deployments & Service Meshes',
        description: 'Pods, Deployments, Services, Ingress controllers, ConfigMaps, Secrets, and rolling zero-downtime updates.',
        estimatedHours: 24,
        skills: ['Kubernetes', 'Ingress', 'ConfigMaps', 'Helm Charts'],
      },
      {
        id: 'ms-devops-4',
        title: 'CI/CD Pipelines, Terraform IaC & Monitoring',
        description: 'GitHub Actions automated testing/deployments, Terraform provisioning on GCP/AWS, and Prometheus/Grafana alerts.',
        estimatedHours: 22,
        skills: ['GitHub Actions', 'Terraform', 'Prometheus', 'Grafana'],
      },
    ],
  },
];
